version: "3.8"


services:

  test-billing-service-api:
    container_name: test-billing-service-api
    build:
      context: .
      dockerfile: infra/backend-test/Dockerfile
    networks:
      - test-billing-service-network
    volumes:
      - ./pytest-reports/:/opt/app/pytest-reports
    env_file:
      - ./src/.env.test
    command: poetry run pytest -p no:cacheprovider --html=pytest-reports/pytest-report.html

networks:
  test-billing-service-network:
    external: true
volumes:
  test_db_data:
