"""Add last_check to UserSubscription

Revision ID: 577c8e189680
Revises: cd9807ed90b2
Create Date: 2023-10-05 13:54:54.135017

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '577c8e189680'
down_revision: Union[str, None] = 'cd9807ed90b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_subscriptions',
        sa.Column('last_check', postgresql.TIMESTAMP(), nullable=True, comment='Дата последней проверки подписки'),
    )
    op.alter_column(
        'user_subscriptions',
        'renew_try_count',
        existing_type=sa.INTEGER(),
        comment='Количество совершённых попыток автопродления платежа',
        existing_comment='Вкл/Выкл автопродление подписки',
        existing_nullable=False,
        existing_server_default=sa.text('0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_subscriptions',
        'renew_try_count',
        existing_type=sa.INTEGER(),
        comment='Вкл/Выкл автопродление подписки',
        existing_comment='Количество совершённых попыток автопродления платежа',
        existing_nullable=False,
        existing_server_default=sa.text('0'),
    )
    op.drop_column('user_subscriptions', 'last_check')
    # ### end Alembic commands ###
