"""fix_payment

Revision ID: 0ecc0aa5d9f0
Revises: 04e65071a096
Create Date: 2023-10-01 21:27:45.534426

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ecc0aa5d9f0'
down_revision: Union[str, None] = '04e65071a096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'pay_status',
        'name',
        existing_type=sa.VARCHAR(length=127),
        comment='Название платежной системы',
        existing_comment='Название платёжной системы',
        existing_nullable=False,
    )
    op.add_column(
        'user_subscriptions',
        sa.Column('user_payment_id', sa.UUID(), nullable=False, comment='Связь с платежом пользователя'),
    )
    op.create_foreign_key(
        None,
        'user_subscriptions',
        'user_payments',
        ['user_payment_id'],
        ['id'],
        onupdate='RESTRICT',
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.drop_column('user_subscriptions', 'user_payment_id')
    op.alter_column(
        'pay_status',
        'name',
        existing_type=sa.VARCHAR(length=127),
        comment='Название платёжной системы',
        existing_comment='Название платежной системы',
        existing_nullable=False,
    )
    # ### end Alembic commands ###
